import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ClerkProvider, SignedIn } from "@clerk/nextjs";
import { UserButton } from "@clerk/nextjs";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Chat App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="w-screen h-screen flex justify-start items-center">
          {children}
          <div className="absolute top-1 right-1 w-[10%] h-[10%] flex justify-center items-center">
            <SignedIn>
              <UserButton
                  appearance={{
                    elements: {
                      userButtonAvatarBox: {
                        width: '100%', 
                        height: '100%',
                        minWidth: '1.5rem',
                        minHeight: '1.5rem',
                        maxWidth: '4rem',
                        maxHeight: '4rem' 
                        },
                      },
                    }}
                  />
            </SignedIn>
          </div>
        </div>
      </body>
    </html>
    </ClerkProvider>
  );
}
